#
# SPDX-License-Identifier: GPL-2.0
# 
# GNUWeebBot (GNUWeeb Telegram Bot)
# 
# https://github.com/GNUWeeb/GNUWeebBot
#

INCLUDE_DIR += -I$(BASE_DIR)/src/ext/openssl_1.1.1j/include
DEP_DIRS	+= $(BASE_DEP_DIR)/src/ext/openssl_1.1.1j
