#
# SPDX-License-Identifier: GPL-2.0
# 
# GNUWeebBot (GNUWeeb Telegram Bot)
# 
# https://github.com/GNUWeeb/GNUWeebBot
#

INCLUDE_DIR	+= -I$(BASE_DIR)/src/ext

DEP_DIRS	+= $(BASE_DEP_DIR)/src/ext/inih
OBJ_CC		+= $(BASE_DIR)/src/ext/inih/inih.o
