#
# SPDX-License-Identifier: GPL-2.0
# 
# GNUWeebBot (GNUWeeb Telegram Bot)
# 
# https://github.com/GNUWeeb/GNUWeebBot
#

DEP_DIRS	+= $(BASE_DEP_DIR)/src/gwbot/modules

include $(BASE_DIR)/src/gwbot/modules/000_debug/Makefile
include $(BASE_DIR)/src/gwbot/modules/001_standard/Makefile
include $(BASE_DIR)/src/gwbot/modules/002_translate/Makefile
include $(BASE_DIR)/src/gwbot/modules/003_admin/Makefile
